################################################################################
# FILE: testsettings.properties                                  
# PATH: 
# ENV : DEFAULT           
#
# Notes:
# > 
################################################################################

#REPORT_DEFINITION_PATH
REPORT_DEFINITION_PATH=./source/org/pentaho/reporting/engine/classic/testcases/samplereport

#REPORT_INPUT_PATH
REPORT_INPUT_PATH=./source/org/pentaho/reporting/engine/classic/testcases/samplereport/golden/windows

#REPORT_OUTPUT_PATH
REPORT_OUTPUT_PATH=./reportoutput